seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 5900
  links:
    - seleniumhub:hub
    
firefoxnode:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  links:
    - seleniumhub:hub
